language: java
before_install:
  - chmod +x mvnw

addons:
  sonarcloud:
    organization: "tdevilleduc"
    token:
      secure: "d8363e498a11c57a4a5402e11c42dcab669c767b" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
